package neu.edu.Entity;
// Generated Dec 9, 2016 12:13:39 AM by Hibernate Tools 5.1.0.CR1

/**
 * Orderitem generated by hbm2java
 */
public class Orderitem implements java.io.Serializable {

	private Integer orderItemId;
	private Order order;
	private Product product;
	private Integer quantityOrdered;
	private Float total;
	private String status;

	public Orderitem() {
	}

	public Orderitem(Order order, Product product, Integer quantityOrdered, Float total, String status) {
		this.order = order;
		this.product = product;
		this.quantityOrdered = quantityOrdered;
		this.total = total;
		this.status = status;
	}

	public Integer getOrderItemId() {
		return this.orderItemId;
	}

	public void setOrderItemId(Integer orderItemId) {
		this.orderItemId = orderItemId;
	}

	public Order getOrder() {
		return this.order;
	}

	public void setOrder(Order order) {
		this.order = order;
	}

	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	public Integer getQuantityOrdered() {
		return this.quantityOrdered;
	}

	public void setQuantityOrdered(Integer quantityOrdered) {
		this.quantityOrdered = quantityOrdered;
	}

	public Float getTotal() {
		return this.total;
	}

	public void setTotal(Float total) {
		this.total = total;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
