language: node_js
cache:
  directories:
    - node_modules
deploy:
- provider: s3
  access_key_id: AKIAICM74QRXLMMRZ3FQ
  secret_access_key: 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
  local_dir: dpl_cd_upload
  skip_cleanup: true
  on: &2
    repo: divyag265/neu-csye6225-4
  bucket: s3.neu-csye6225-spring2017-team6.com
  region: us-east-1
- provider: codedeploy
  access_key_id: AKIAICM74QRXLMMRZ3FQ
  secret_access_key: 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
  bucket: s3.neu-csye6225-spring2017-team6.com
  key: latest.zip
  bundle_type: zip
  application: HotelApplication
  deployment_group: HotelApplication
  region: us-west-2
  on: *2
script:
  - zip -r latest *
  - mkdir -p dpl_cd_upload
  - mv latest.zip dpl_cd_upload/latest.zip
