language: node_js
cache:
  directories:
    - node_modules
after_success:
- mkdir -p codedeploy
- pwd
- ls -al
- zip -r latest public/angular-app/main appspec.yml
- ls -al
- mv latest.zip codedeploy
- ls -al
- pwd
- cd codedeploy
- ls -al
- pwd
before_deploy:
- cd ..
deploy:
- provider: s3
  access_key_id: AKIAIVF7AQHGKYQQOICQ
  secret_access_key: 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
  local_dir: codedeploy
  skip_cleanup: true
  on: &2
    repo: divyag265/neu-csye6225-4
  bucket: s3.neu-csye6225-spring2017-team6.com
  region: us-east-1
- provider: codedeploy
  access_key_id: AKIAIVF7AQHGKYQQOICQ
  secret_access_key: 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
  bucket: s3.neu-csye6225-spring2017-team6.com
  key: latest.zip
  bundle_type: zip
  application: Application
  deployment_group: DeploymentGroup
  region: us-east-1
  on: *2
#before_script: 'npm test'
#script:
#  - npm test
#  - zip -r latest *
#  - mkdir -p dpl_cd_upload
#  - mv latest.zip dpl_cd_upload/latest.zip
