version: 0.0
os: linux
files:
  - source: index.html
    destination: /var/www/html/hotelApplication/
  - source: salt/
    destination: /etc/hotelApplication/codedeploy/
hooks:
  AfterInstall:
    - location: deploy_hooks/afterinstall.sh
    - runas: root
