version: 0.0
os: linux
  files:
  - source: /
    destination: /home/ubuntu
  - source: main
    destination: /Cloud-Project/neu-csye6225-4
  hooks:
    AfterInstall:
    - location: deploy_hooks/afterinstall.sh
      runas: root
