version: 0.0
os: linux
files:
  - source: index.html
    destination: /var/www/html/hotelApplication/
  - source: salt/
    destination: /etc/hotelApplication/codedeploy/
hooks:
  BeforeInstall:
    - location: deploy_hooks/before_install.sh
    runas: root
  ApplicationStart:
    - location: deploy_hooks/application_start.sh
      runas: root
  ValidateService:
    - location: deploy_hooks/verify_service.sh
      runas: root

