package neu.edu.Entity;
// Generated Dec 9, 2016 12:13:39 AM by Hibernate Tools 5.1.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
public class Product implements java.io.Serializable {

	private Integer productId;
	private Seller seller;
	private String name;
	private String description;
	private Float price;
	private Integer quantityAvail;
	private Set<Orderitem> orderitems = new HashSet<Orderitem>(0);

	public Product() {
	}

	public Product(Seller seller, String name, String description, Float price, Integer quantityAvail,
			Set<Orderitem> orderitems) {
		this.seller = seller;
		this.name = name;
		this.description = description;
		this.price = price;
		this.quantityAvail = quantityAvail;
		this.orderitems = orderitems;
	}

	public Integer getProductId() {
		return this.productId;
	}

	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	public Seller getSeller() {
		return this.seller;
	}

	public void setSeller(Seller seller) {
		this.seller = seller;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Float getPrice() {
		return this.price;
	}

	public void setPrice(Float price) {
		this.price = price;
	}

	public Integer getQuantityAvail() {
		return this.quantityAvail;
	}

	public void setQuantityAvail(Integer quantityAvail) {
		this.quantityAvail = quantityAvail;
	}

	public Set<Orderitem> getOrderitems() {
		return this.orderitems;
	}

	public void setOrderitems(Set<Orderitem> orderitems) {
		this.orderitems = orderitems;
	}

}
