package neu.edu.Entity;
// Generated Dec 9, 2016 12:13:39 AM by Hibernate Tools 5.1.0.CR1

/**
 * Admin generated by hbm2java
 */
public class Admin implements java.io.Serializable {

	private int adminId;
	private User user;

	public Admin() {
	}

	public Admin(User user) {
		this.user = user;
	}

	public int getAdminId() {
		return this.adminId;
	}

	public void setAdminId(int adminId) {
		this.adminId = adminId;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

}
