package neu.edu.Entity;
// Generated Dec 9, 2016 12:13:39 AM by Hibernate Tools 5.1.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Customer generated by hbm2java
 */
public class Customer implements java.io.Serializable {

	private int customerId;
	private User user;
	private String dob;
	private String gender;
	private Integer cardNumber;
	private Integer cvv;
	private String expDate;
	private Set<Order> orders = new HashSet<Order>(0);

	public Customer() {
	}

	public Customer(User user) {
		this.user = user;
	}

	public Customer(User user, String dob, String gender, Integer cardNumber, Integer cvv, String expDate,
			Set<Order> orders) {
		this.user = user;
		this.dob = dob;
		this.gender = gender;
		this.cardNumber = cardNumber;
		this.cvv = cvv;
		this.expDate = expDate;
		this.orders = orders;
	}

	public int getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(int customerId) {
		this.customerId = customerId;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getDob() {
		return this.dob;
	}

	public void setDob(String dob) {
		this.dob = dob;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public Integer getCardNumber() {
		return this.cardNumber;
	}

	public void setCardNumber(Integer cardNumber) {
		this.cardNumber = cardNumber;
	}

	public Integer getCvv() {
		return this.cvv;
	}

	public void setCvv(Integer cvv) {
		this.cvv = cvv;
	}

	public String getExpDate() {
		return this.expDate;
	}

	public void setExpDate(String expDate) {
		this.expDate = expDate;
	}

	public Set<Order> getOrders() {
		return this.orders;
	}

	public void setOrders(Set<Order> orders) {
		this.orders = orders;
	}

}
