package neu.edu.Entity;
// Generated Dec 9, 2016 12:13:39 AM by Hibernate Tools 5.1.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Order generated by hbm2java
 */
public class Order implements java.io.Serializable {

	private Integer orderId;
	private Customer customer;
	private Date dateCreated;
	private Date dateShipped;
	private Float orderToal;
	private Set<Orderitem> orderitems = new HashSet<Orderitem>(0);

	public Order() {
	}

	public Order(Customer customer, Date dateCreated, Date dateShipped, Float orderToal, Set<Orderitem> orderitems) {
		this.customer = customer;
		this.dateCreated = dateCreated;
		this.dateShipped = dateShipped;
		this.orderToal = orderToal;
		this.orderitems = orderitems;
	}

	public Integer getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	public Date getDateShipped() {
		return this.dateShipped;
	}

	public void setDateShipped(Date dateShipped) {
		this.dateShipped = dateShipped;
	}

	public Float getOrderToal() {
		return this.orderToal;
	}

	public void setOrderToal(Float orderToal) {
		this.orderToal = orderToal;
	}

	public Set<Orderitem> getOrderitems() {
		return this.orderitems;
	}

	public void setOrderitems(Set<Orderitem> orderitems) {
		this.orderitems = orderitems;
	}

}
